apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  template:
    metadata:
      name: postgres
      labels:
        name: postgres
    spec:
      containers:
        - image: postgres:9.5.3
          name: postgres
          env:
            - name: POSTGRES_PASSWORD
              value: sonar
            - name: POSTGRES_USER
              value: sonar 
            - name: POSTGRES_DB
              value: sonar
          ports:
            - containerPort: 5432
              name: postgresport

